BicycletteBleue -Django/location/urls.py
"""
Auteur : Daniele Castro
"""

from django.urls import path, include
from . import views

app_name = 'location'

urlpatterns = [
    path('',views.location, name='index'),
    path('locationEnAttente/', views.locationEnAttente, name='locationEnAttente'),
    path('<int:id>/', views.detailsLocation, name='detailsLocation'),
    path('detailsLocationEnAttente/<int:id>', views.detailsLocationEnAttente, name='detailsLocationEnAttente'),
    path('confirmationLocation/<str:pk>', views.confirmationLocation, name='confirmationLocation'),
    path('nouvelleLocation/', views.nouvelleLocation, name='nouvelleLocation'),
    path('modifierLocation/<str:pk>', views.modifierlocation, name='modifierLocation'),
    path('supprimerLocation/<str:pk>',views.supprimerLocation, name='supprimerLocation'),
    path('refuseLocationEnAttente/<str:pk>',views.refuseLocationEnAttente, name='refuseLocationEnAttente'),



    path('locationClient/<str:pk>',views.locationClient, name='locationClient'),
    path('detailsLocation/<int:id>', views.detailsLocationClient, name='detailsLocationClient'),
    path('nouvelleLocationClient/', views.choixVeloClient, name='choixVeloClient'),
    path('modifierLocationClient/<str:pk>', views.modifierlocationClient, name='modifierLocationClient'),
    path('supprimerLocationClient/<str:pk>', views.supprimerLocationClient, name='supprimerLocationClient'),
    path('finaliserLocationClient/<str:pk>', views.finaliserLocationClient, name='finaliserLocationClient'),
    path('choixVelo/', views.choixVeloClient, name='choixVeloClient'),
    path('donneeLocationClient/<str:pk>', views.donneeLocationClient, name='donneeLocationClient'),
]

BicycletteBleue -Django/location/templates/location/choixVeloClient.html
<!---
Auteur : Daniele Castro
-->



{% extends 'template_base.html' %}
{% load static %}

{% block contenu %}

<!-- Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">

<!-- CSS Libraries -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
<link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">


<br>

<br>
<!--
<div class="container bootstrap snipets">

  <br>

   <div class="row flow-offset-1" >
     {% for velo in veloDispo %}
     <div class="col-xs-6 col-md-4" >
       <div class="product tumbnail thumbnail-3"><a href="{% url 'stock_velos:indexDetailsVelo' velo.vel_num%}"><img src="{% static 'img/velo/velo1.png' %}" alt="" style="width: 350px; height: 280px"></a>
         <div class="caption">
             <h6><a href="#">{{velo.vel_marque}}</a></h6><span class="price"></span>
             <a>Type de vélo : {{velo.vel_type}}</a><br>
             <a href="{% url 'stock_velos:indexDetailsVelo' velo.vel_id%}">Details</a>
         </div>
       </div>
     </div>
     {% endfor %}
   </div>
 </div>
-->
<h1 class="titre" style="text-align: center; color: #1F35A5" >Commencez par choisir un vélo</h1>
<h6 style="text-align: center; color: red"> {{messageAttention}}</h6>
{% if messageAttention != "" %}
    <h6 style="text-align: center; color: red"><a href="{% url 'location:locationClient'  request.user.id %}">Voir mes locations.</a></h6>
{% endif %}
<br>
<br>


<style>
    body{
    background:#f5f5f5;
    margin-top:20px;}

.card-img-tiles {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    position: relative;
    background-color: #fff;
    z-index: 5
}

.card-img-tiles .main-img>img,
.card-img-tiles .thumblist>img {
    display: block;
    width: 100%
}

.card-img-tiles .main-img {
    width: 67%;
    padding-right: .375rem
}

.card-img-tiles .thumblist {
    width: 33%;
    padding-left: .375rem
}

.card-img-tiles .thumblist>img {
    margin-bottom: .75rem
}

.card-img-tiles .thumblist>img:last-child {
    margin-bottom: 0
}

.mb-grid-gutter {
    margin-bottom: 30px !important;
}

</style>

   <div style="border: 1px solid ; margin-left: 22%; margin-right: 22%">
   <table class="table table-hover">
    <thead>
    <h4 style="text-align: center">Rappel des tarifs des locations</h4>
    </thead>
    <thead>
    <tr>
      <th scope="col">3 mois (le minimum)</th>
      <th scope="col">rajout d'un mois supplémentaire</th>
      <th scope="col">caution</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>50 CHF</td>
      <td>+5 CHF</td>
      <td>150 CHF</td>
    </tr>
  </tbody>
</table>
</div>
<br><br>

<div class="container pb-5 mb-sm-1">
    <!-- Categories grid-->
    <div class="row">
        <!-- Category-->
        {% for velo in veloDispo %}
        <div class="col-md-4 col-sm-6">
            <div class="card border-0 mb-grid-gutter">
                <img src="{% static 'img/velo/velo1.png' %}" alt="Clothing" style="width: 350px; height: 280px">
                <div class="card-body border mt-n1 py-4 text-center">
                    <h2 class="h5 mb-1" style="color: #1F35A5">{{velo.vel_marque}}</h2><span class="d-block mb-3 font-size-xs text-muted"> Type : {{velo.vel_type}}</span>
                    <a class="btn btn-pill btn-outline-primary btn-sm" href="{% url 'stock_velos:indexDetailsVeloClient' velo.vel_num%}" >Détails</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock contenu %}

BicycletteBleue -Django/location/templates/location/confirmationLocation.html
<!---
Auteur : Daniele Castro
-->

{% extends 'template_base.html' %}
{% load static %}
{% block contenu %}
        <!-- Google Font -->
        <!-- CSS Libraries -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

<br>
<h4 style="margin-left: 22%">Voulez-vous confirmer cette location?</h4>
<br>
<form action="{% url 'location:confirmationLocation' itemLocation.loc_num %}"  method="post">
    {% csrf_token %}
<table class="table">
  <thead class="thead-dark" >
    <tr>
      <th scope="col">Statut location</th>
      <th scope="col">Nom Prenom client</th>
      <th scope="col">Nom vélo</th>
      <th scope="col">Date début</th>
      <th scope="col">Date fin</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>{{itemLocation.loc_statut}}</td>
        <td>{{itemLocation.loc_client.cli_nom}} {{itemLocation.loc_client.cli_prenom}}</td>
        <td>{{itemLocationVelo.lv_vel_id}}</td>
        <td>{{itemLocationVelo.date_debut}}</td>
        <td>{{itemLocationVelo.date_fin}}</td>
    </tr>
  </tbody>
</table>
    <br>
    <a href="{% url 'location:locationEnAttente'%}"  class="btn btn-primary" style="margin-left: 22%">Annuler</a>
    <input class="btn btn-primary" type="submit" value="Confirmer" name="Confirmer" >
</form>

{% endblock %}

BicycletteBleue -Django/location/templates/location/finaliserLocationClient.html
<!---
Auteur : Daniele Castro
-->


{% extends 'template_base.html' %}
{% load static %}


{% block contenu %}
<!-- Google Font -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

<br>
<h1 style="margin-left: 22%">Finalisez votre location</h1>
<br>
<br>

<form style="margin-left: 25% ; margin-right: 30%" action="" method="POST">
     {%  csrf_token %}
  <div class="form-group">
    <label>Date de debut<sup style="color: red">*</sup> :</label>
    <input  id="dateDebut" class="form-control" type="date" placeholder="Date debut" for={{formLocationVelo.date_debut}}
  </div>
  <div id ="dateFinDiv"   class="form-group">
    <label>Date de fin<sup style="color: red">*</sup> :</label>
    <input  id="dateFin"  style="margin-bottom:2%" class="form-control" type="date" placeholder="Date fin" for={{formLocationVelo.date_fin}}
  </div>

  <a style="color: red">{{messageErreur}}</a><br><br>
     <sup style="color: red ;">*Champs obligatoires</sup>


      <div style="border: 1px solid">
        <table class="table table-hover">
    <thead>
    <h4 style="text-align: center">Rappel des tarifs des locations</h4>
    </thead>
    <thead>
    <tr>
      <th scope="col">3 mois (le minimum)</th>
      <th scope="col">rajout d'un mois supplémentaire</th>
      <th scope="col">caution</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>50 CHF</td>
      <td>+5 CHF</td>
      <td>150 CHF</td>
    </tr>
  </tbody>
</table>
</div>
<br><br>
  <a href="{% url 'location:donneeLocationClient' velo.vel_id%}" class="btn btn-primary" role="button" aria-pressed="true" >Annuler</a>
  <input id="btnEnvoyer" type="submit" value="Envoyer" class="btn btn-primary" href="{% url 'location:finaliserLocationClient' velo.vel_id%}" >
</form>



<script type="text/javascript">
      document.getElementById("btnEnvoyer").disabled = true;
      var newDiv = document.createElement("div");
      newDiv.setAttribute("id", "divJs");
      var dateFinDiv = document.getElementById('dateFinDiv');
      dateFinDiv.appendChild(newDiv); // Permet de rajouter une nouvelle div dans la div ou il y a l'input de la date de fin (en tant qu'enfant) et devient donc le frère/soeur de l'input
      var a = '';
      var dateDebut  = document.getElementById("dateDebut");
      var dateFin   = document.getElementById("dateFin");
      var textAfficher = ''; // Variable qui permet de stocker ce que nous allons afficher
      // Permet d'afficher lorsque nous modifions la date de debut et la date de fin
      var afficher = function () {
        // Permet de calculer la différence entre deux dates
        var diff_en_temps = new Date(dateFin.value).getTime() - new Date(dateDebut.value).getTime();
        var diff_en_jours = diff_en_temps / (1000 * 3600 * 24);
        // Permet de rien afficher si une seule des deux date est entrée.
        if (isNaN(diff_en_jours)){
            textAfficher = '';
        }
        // si les deux date sont entrées alors ..
        else{
            // si la différence de date dépasse les 1 ans ...
            if (diff_en_jours > 365){
              textAfficher = 'ATTENTION : la location ne doit pas dépasser 1 an.';
                document.getElementById("btnEnvoyer").disabled = true;}
            // si la différence est d'au moins 90 jours(3 mois) ..
            else if (diff_en_jours > 90){
              document.getElementById("btnEnvoyer").disabled = false;
              var somme = 50; // les trois mois de départ
              var jours = diff_en_jours - 90 // enlever les 3 mois minimum pour avoir unqiuement les jours en plus 
              somme += Math.round(jours / 30) * 5 // calcul de la somme 
              textAfficher = "Total de la location : "+ somme + " + 150 (la caution) = " + (somme + 150) + " CHF";
            }
            // si la différence de jours est en dessous de 3 mois alors..
            else{textAfficher = 'ATTENTION : la location doit durer au minimum 3 mois.';
                document.getElementById("btnEnvoyer").disabled = true;}
        }
        // permet d'afficher le texte adéquat avec une nouvelle balise "h6"
          if (a === ''){
           var newH6 = document.createElement("H6");
           newH6.setAttribute("id", "H6div");
           newDiv.appendChild(newH6);
           newH6.innerHTML = textAfficher;
           a = "a";
        }
          else{
           document.getElementById("H6div").innerHTML = textAfficher;
        }
        }
      //lorsqu'on change un des deux input nous entrons dans la fonction "afficher"
      dateDebut.addEventListener("change", afficher);
      dateFin.addEventListener("change", afficher);

   </script>
{% endblock %}

BicycletteBleue -Django/location/templates/location/location.html
<!---
Auteur : Daniele Castro
-->


{% extends 'template_base.html' %}
{% load static %}
{% load mathfilters %}
{% block contenu %}

<!-- CSS Libraries -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
<link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <br>
<h1 class="titre" style="margin-left: 10%">Liste des locations</h1>
    <br>
<br>
<form method="get">
<div class="btn-group btn-group-sm mb-3" role="group" aria-label="Groupe de petits boutons" style="margin-left: 10%">
{{myfilter.form}}&nbsp;
<button class="btn btn-primary" type="submit" style="" >Filtrer</button></div>
</form>

<div class="table-responsive">
 <table class="table">
  <thead class="thead-dark" >
    <tr>
      <th scope="col">Numéro location</th>
      <th scope="col">Statut location</th>
      <th scope="col">Nom client</th>
      <th scope="col">Nom vélo</th>
      <th scope="col">Date début</th>
      <th scope="col">Date fin</th>
      <th scope="col">Temps restant</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for loc in locations %}
    <tr>
      <th scope="row">{{ loc.lv_loc_id.loc_num}}</th>
      <td><a href="{% url 'location:detailsLocation' loc.loc_num %}">{{ loc.lv_loc_id.loc_statut}}</a></td>
      <td><a>{{loc.lv_loc_id.loc_client.cli_nom}} {{loc.lv_loc_id.loc_client.cli_prenom}}</a></td>
      <td>{{loc.lv_vel_id.vel_nom}}</td>
      <td>{{loc.date_debut}}</td>
      <td>{{loc.date_fin}}</td>
      {% if not loc.ends_within_10_days and not loc.termine and not loc.annule%}
        <td style="color: green">{{loc.date_fin|timeuntil:date}}</td>
      {% elif loc.termine %}
        <td style="color: blue">Terminé</td>
      {% elif loc.annule %}
        <td style="color: blue">Annulé</td>
      {% else %}
        <td style="color: red">{{loc.date_fin|timeuntil:date}}</td>
      {% endif %}
      <td><a href="{% url 'location:modifierLocation'  loc.loc_num%}">Modifier</a></td>
      <td><a href="{% url 'location:supprimerLocation' loc.loc_num%}"><img class="imagePoubelle" src="{% static 'img/poubelle.png' %}" alt="Image"></a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
</div>
<br>




<!-- Button -->
<a href="{% url 'location:nouvelleLocation' %}" class="btn btn-primary" role="button" aria-pressed="true" style="margin-left: 10% ;margin-bottom:20px">Ajouter une nouvelle location</a>

<br><br><br><br><br><br>

<h3 class="titre" style="margin-left: 10%">{{ messageNbLocation }}</h3>


<br><br><br><br><br>

{% endblock %}

BicycletteBleue -Django/location/templates/location/locationClient.html
<!---
Auteur : Daniele Castro
-->


{% extends 'template_base.html' %}
{% load static %}
{% load mathfilters %}
{% block contenu %}

<!-- CSS Libraries -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
<link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

<br>
<h1 style="margin-left: 10%">Liste des locations</h1>
<br>
<h3 style="margin-left: 10%">Vous avez {{ messageNbLocation }}</h3>
<br>

<br>

<div class="table-responsive">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Numéro location</th>
      <th scope="col">Statut location</th>
      <th scope="col">Nom client</th>
      <th scope="col">Nom vélo</th>
      <th scope="col">Date début</th>
      <th scope="col">Date fin</th>
      <th scope="col">Temps restant</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for locationvelo in locations %}
    <tr>
      <th scope="row">{{ locationvelo.lv_loc_id.loc_num}}</th>
      <td><a href="{% url 'location:detailsLocationClient' locationvelo.loc_num %}">{{ locationvelo.lv_loc_id.loc_statut}}</a></td>
      <td><a>{{locationvelo.lv_loc_id.loc_client.cli_nom}} {{locationvelo.lv_loc_id.loc_client.cli_prenom}}</a></td>
      <td>{{locationvelo.lv_vel_id.vel_nom}}</td>
      <td>{{locationvelo.date_debut}}</td>
      <td>{{locationvelo.date_fin}}</td>



      {% if not locationvelo.ends_within_10_days and not locationvelo.termine and not locationvelo.annule%}
        <td style="color: green">{{locationvelo.date_fin|timeuntil:date}}</td>
      {% elif locationvelo.termine %}
        <td style="color: blue">Terminé</td>
      {% elif locationvelo.annule %}
        <td style="color: blue">Annulé</td>
      {% else %}
        <td style="color: red">{{locationvelo.date_fin|timeuntil:date}}</td>
      {% endif %}

      {% if not locationvelo.termine and not locationvelo.annule %}
        <td><a href="{% url 'location:modifierLocationClient'  locationvelo.loc_num%}">Diminuer/Prolonger</a></td>
        <td><a href="{% url 'location:supprimerLocationClient' locationvelo.loc_num%}"><img class="imagePoubelle" src="{% static 'img/poubelle.png' %}" alt="Image"></a></td>
      {% else %}
        <td> </td>
        <td></td>
      {% endif %}
    </tr>
  {% endfor %}
  </tbody>
</table>
</div>



<!-- Button -->
<a href="{% url 'location:choixVeloClient' %}" class="btn btn-primary" role="button" aria-pressed="true" style="margin-left: 10%">Ajouter une nouvelle location</a>

<br>


{% endblock %}

BicycletteBleue -Django/location/templates/location/locationEnAttente.html
<!---
Auteur : Daniele Castro
-->


{% extends 'template_base.html' %}
{% load static %}
{% load mathfilters %}
{% block contenu %}

<!-- CSS Libraries -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
<link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">



    <br>
<h1 class="titre" style="margin-left: 10%">Liste des locations en attente</h1>
    <br>

<br>
<div class="table-responsive">
 <table class="table">
  <thead class="thead-dark" >
    <tr>
      <th scope="col">Numéro location</th>
      <th scope="col">Statut location</th>
      <th scope="col">Nom client</th>
      <th scope="col">Nom vélo</th>
      <th scope="col">Date début</th>
      <th scope="col">Date fin</th>
      <th scope="col">Ancienne date</th>
      <th scope="col">Temps de la diminution/prolongation</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for loc in locationEnattente %}
    <tr>
      <th scope="row">{{ loc.lv_loc_id.loc_num}}</th>
      <td><a href="{% url 'location:detailsLocationEnAttente' loc.loc_num %}">{{ loc.lv_loc_id.loc_statut}}</a></td>
      <td><a>{{loc.lv_loc_id.loc_client.cli_nom}} {{loc.lv_loc_id.loc_client.cli_prenom}}</a></td>
      <td>{{loc.lv_vel_id.vel_nom}}</td>
      <td>{{loc.date_debut}}</td>
      <td>{{loc.date_fin}}</td>
          {% if loc.lv_loc_id.date_modifier != None%}
          <td>{{loc.lv_loc_id.date_modifier}}</td>
          <td>
                {{loc.date_fin|timeuntil:loc.lv_loc_id.date_modifier}}
          </td>
          {% else %}
          <td>-</td>
          <td>-</td>
          {% endif %}
      <td><a href="{% url 'location:confirmationLocation'  loc.loc_num%}">Confirmer</a></td>
      <td><a href="{% url 'location:refuseLocationEnAttente' loc.loc_num%}">Refusé</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
</div>
<br>




<br><br><br><br><br><br>

<h3 class="titre" style="margin-left: 10%">{{ messageNbLocation }}</h3>


{% endblock %}

BicycletteBleue -Django/location/templates/location/refuseLocationEnAttente.html
<!---
Auteur : Daniele Castro
-->

{% extends 'template_base.html' %}
{% load static %}
{% block contenu %}
        <!-- Google Font -->
        <!-- CSS Libraries -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

<br>
<h4 style="margin-left: 22%">Voulez-vous annuler cette location?</h4>
<br>
<form action="{% url 'location:refuseLocationEnAttente' itemLocation.loc_id %}"  method="post">
    {% csrf_token %}
<table class="table">
  <thead class="thead-dark" >
    <tr>
      <th scope="col">Statut location</th>
      <th scope="col">Nom Prenom client</th>
      <th scope="col">Nom vélo</th>
      <th scope="col">Date début</th>
      <th scope="col">Date fin</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>{{itemLocation.loc_statut}}</td>
        <td>{{itemLocation.loc_client.cli_nom}} {{itemLocation.loc_client.cli_prenom}}</td>
        <td>{{itemLocationVelo.lv_vel_id}}</td>
        <td>{{itemLocationVelo.date_debut}}</td>
        <td>{{itemLocationVelo.date_fin}}</td>
    </tr>
  </tbody>
</table>
    <br>
    <a href="{% url 'location:locationEnAttente'%}"  class="btn btn-primary" style="margin-left: 22%">Annuler</a>
    <input class="btn btn-primary" type="submit" value="Confirmer" name="Confirmer" >
</form>

{% endblock %}

BicycletteBleue -Django/location/templates/location/supprimerLocation.html
<!---
Auteur : Daniele Castro
-->

{% extends 'template_base.html' %}
{% load static %}
{% block contenu %}
        <!-- Google Font -->
        <!-- CSS Libraries -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

<br>
<h4 style="margin-left: 22%">Voulez-vous vraiment supprimer cette location?</h4>
<br>
<form action="{% url 'location:supprimerLocation' itemLocation.loc_num %}"  method="post">
    {% csrf_token %}
<table class="table">
  <thead class="thead-dark" >
    <tr>
      <th scope="col">Statut location</th>
      <th scope="col">Nom client</th>
      <th scope="col">Nom vélo</th>
      <th scope="col">Date début</th>
      <th scope="col">Date fin</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>{{itemLocation.loc_statut}}</td>
        <td>{{itemLocation.loc_client.cli_nom}}</td>
        <td>{{itemLocationVelo.lv_vel_id}}</td>
        <td>{{itemLocationVelo.date_debut}}</td>
        <td>{{itemLocationVelo.date_fin}}</td>
    </tr>
  </tbody>
</table>
    <br>
    <a href="{% url 'location:index'%}"  class="btn btn-primary" style="margin-left: 22%">Annuler</a>
    <input class="btn btn-danger" type="submit" value="Supprimer" name="Confirmer" >
</form>

{% endblock %}

BicycletteBleue -Django/location/templates/location/supprimerLocationClient.html
<!---
Auteur : Daniele Castro
-->


{% extends 'template_base.html' %}
{% load static %}
{% block contenu %}
        <!-- Google Font -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

<br>
<h4 style="margin-left: 22%">Voulez-vous vraiment supprimer cette location?</h4>
<br>
<form action="{% url 'location:supprimerLocationClient' itemLocation.loc_id %}"  method="post">
    {% csrf_token %}
<table class="table">
  <thead class="thead-dark" >
    <tr>
      <th scope="col">Statut location</th>
      <th scope="col">Nom client</th>
      <th scope="col">Nom vélo</th>
      <th scope="col">Date début</th>
      <th scope="col">Date fin</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>{{itemLocation.loc_statut}}</td>
        <td>{{itemLocation.loc_client.cli_nom}}</td>
        <td>{{itemLocation.loc_client.cli_prenom}}</td>
        <td>{{itemLocationVelo.date_debut}}</td>
        <td>{{itemLocationVelo.date_fin}}</td>
    </tr>
  </tbody>
</table>
    <a href="{% url 'location:locationClient' request.user.id %}"  class="btn btn-primary" style="margin-left: 22%">Annuler</a>
    <input class="btn btn-danger" type="submit" value="Supprimer" name="Confirmer" >
</form>

{% endblock %}