BicycletteBleue -Django/stock_pieces_velos/urls.py
from django.urls import path, include
from . import views

app_name = 'stock_pieces_velos'

urlpatterns = [
    path('', views.stock_pieces_velos, name='indexStockPiecesVelos'),
    path('nouvelle_piece/', views.nouvelle_piece, name='indexNouvellePiece'),
    path('supprimer_piece/<str:num>', views.supprimer_piece, name='indexSupprimerPiece'),
    path('modifier_piece/<str:num>', views.modifier_piece, name='indexModifierPiece'),
    path('details_piece/<str:num>', views.details_piece, name='indexDetailsPiece'),
    #path('commander_pieces/<str:num>', views.commander_piece, name='indexCommanderPieces'),
]

BicycletteBleue -Django/stock_pieces_velos/templates/stock_pieces_velos/ajouter_piece.html
<!-- Auteur : Stanley Rochat-->
{% extends 'template_base.html' %}
{% load static %}

{% block contenu %}

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">





<form style="margin-left: 25% ; margin-right: 30%" action="" method="post">
    {% csrf_token %}
    <br>
    <h1> Ajouter une pièce de vélo </h1>
    <br><br>
    <p1> Photo: &nbsp; </p1>
    <div>{{formPiece.piece_photo}}</div>
    <br>


    <div class="form-group">
    <p1>Numéro pièce<p1 style="color: red">*</p1>: &nbsp; </p1>
    <input  class="form-control"  type="text"  for={{formPiece.piece_num_cadre}}
    </div>

    <div class="form-group">
    <p1>Type de pièce<p1 style="color: red">*</p1>: &nbsp; </p1>
    <select  class="form-control"  type="text"  for={{formPiece.piece_type}}
    </div>

    <div class="form-group">
    <p1>Type de vélo<p1 style="color: red">*</p1>: &nbsp; </p1>
    <select  class="form-control"  type="text"  for={{formPiece.piece_type_velo}}
    </div>

    <div class="form-group">
    <p1>Marque de la pièce<p1 style="color: red">*</p1>: &nbsp; </p1>
    <select  class="form-control"  type="text"  for={{formPiece.piece_marque}}
    </div>

    <div class="form-group">
    <p1>Nombre de pièces<p1 style="color: red">*</p1>: &nbsp; </p1>
    <input  class="form-control"  type="text"  for={{formPiece.piece_nb}}
    </div>


    <div class="form-group">
    <p1>Remarque : &nbsp; </p1>
    <input  class="form-control"  type="text"  for={{formPiece.piece_remarque}}
    </div>

    <div class="form-group">
    <p1>Local<p1 style="color: red">*</p1>: &nbsp; </p1>
    <select  class="form-control"  type="text"  for={{formPiece.local_id}}
    </div>

    <div class="form-group">
    <p1>Fourniseur<p1 style="color: red">*</p1>: &nbsp; </p1>
    <select  class="form-control"  type="text"  for={{formPiece.fourni_id}}
    </div>


    <div class="form-group">
    <p1>Commande : &nbsp; </p1>
    <select  class="form-control"  type="text"  for={{formPiece.commande_fourni_id}}
    </div>



<div>
    <a href="{% url 'stock_pieces_velos:indexStockPiecesVelos'%}"  class="btn btn-primary" >Annuler</a>
    <input type="submit" class="btn btn-primary" role="button">
</div>

</form>
<br>

<sup style="color: red ; margin-left: 25%">*Champs obligatoires</sup>


{% endblock %}

BicycletteBleue -Django/stock_pieces_velos/templates/stock_pieces_velos/commander_piece.html
<!---
Auteur : Stanley Rochat
-->


{% extends 'template_base.html' %}
{% load static %}
{% block contenu %}

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">


    <br>
    <h1 class="detailLocation"> Les détails de la pièce :</h1>
    <br>
    <div class="detailLocation">
        <img src="#" alt="" style="width: 350px; height: 280px"><br><br>
        {{piece.piece_photo}} <br>
        Type de pièce : {{ piece.piece_type}} <br>
        N° de la pièce : {{piece.piece_num}} <br>
        Marque : {{ piece.piece_marque}} <br>
        Couleur : {{ piece.piece_couleur }} <br>

        {% if piece.fourni_id %}}
        Fournisseur : {{piece.fourni_id}} <br>
        {% else %}
        Fournisseur : Aucun <br>
        {% endif %}
        <br>
        Nombre de pièces actuellement en stock : {{ piece.piece_ }}
        <br>
        Nombre de pièces désirées: {{formVelo.commande_fourni_id}}


        <a href="{% url 'stock_pieces_velos:indexStockPiecesVelos' %}" class="btn btn-primary" role="button" aria-pressed="true"
           style="margin-top: 2%"> Annuler </a>
        <input type="submit" class="btn btn-primary" role="button">
    </div>

<br><br>




{% endblock contenu %}

BicycletteBleue -Django/stock_pieces_velos/templates/stock_pieces_velos/details_piece.html
<!---
Auteur : Stanley Rochat
-->


{% extends 'template_base.html' %}
{% load static %}
{% block contenu %}

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">


    <br>
    <h1 class="detailLocation"> Les détails de la pièce :</h1>
    <br>
    <div class="detailLocation">
        <img src="#" alt="" style="width: 350px; height: 280px"><br><br>
        {{piece.piece_photo}} <br>
        Type de pièce : {{ piece.piece_type}} <br>
        N° de la pièce : {{piece.piece_num}} <br>
        Local : {{piece.local_id}} <br>

        {% if piece.fourni_id %}
        Fournisseur : {{piece.fourni_id}} <br>
        {% else %}
        Fournisseur : Aucun <br>
        {% endif %}
        <br>
        Type : {{ piece.piece_type }} <br>
        Marque : {{ piece.piece_marque}} <br>
        Couleur : {{ piece.piece_couleur }} <br>
        <br>
        Statut de commande: {{ piece.commande_fourni_id }} <br>

        {% if piece.piece_remarque %}
        Remarques : {{piece.piece_remarque}} <br>
        {% else %}
        Remarques : <br>
        {% endif %}

        <a href="{% url 'stock_pieces_velos:indexStockPiecesVelos' %}" class="btn btn-primary" role="button" aria-pressed="true"
           style="margin-top: 2%"> <--- Retour au stock de velos </a>
    </div>

<br><br>




{% endblock contenu %}

BicycletteBleue -Django/stock_pieces_velos/templates/stock_pieces_velos/stock_pieces_velos.html
<!-- Auteur : Stanley Rochat-->
{% extends 'template_base.html' %}
{% load static %}

{% block contenu %}


        <!-- CSS Libraries -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">



<br>

<h1 style="margin-left: 10%">Stock de pièces de vélo</h1>
<br>
<br>
<table class="table">
  <thead class="thead-dark">
    <tr>
        <th class="ligne0">
            <p1>Photo</p1>
        </th>
        <th class="ligne0">
            <p1>N° pièce</p1>
        </th>
        <th class="ligne0">
            <p1>Type de pièce</p1>
        </th>
        <th class="ligne0">
            <p1>Marque de la pièce</p1>
        </th>
        <th class="ligne0">
            <p1>Type de vélo</p1>
        </th>
        <th class="ligne0">
            <p1>Nombre de pièces</p1>
        </th>
        <th class="ligne0">
            <p1>Remarques</p1>
        </th>
        <th class="ligne0">
            <p1>Fournisseur</p1>
        </th>
        <th class="ligne0">
            <p1>Local</p1>
        </th>
        <th class="ligne0">
            <p1>Commande</p1>
        </th>
        <th class="ligne0">
            <p1></p1>
        </th>
        <th class="ligne0">
            <p1></p1>
        </th>
    </tr>
</thead>
    {% for piece in piecesObjets %}
    <tr>
        <td>
            <p1>{{piece.piece_photo}}</p1>
        </td>
        <td>
            <p1>{{piece.piece_num}}</p1>
        </td>
        <td>
            <p1><a href="{% url 'stock_pieces_velos:indexDetailsPiece' piece.piece_num %}">{{piece.piece_type}}</a></p1>
        </td>
        <td>
            <p1>{{piece.piece_type_velo}}</p1>
        </td>
        <td>
            <p1>{{piece.piece_marque}}</p1>
        </td>
        <td>
            <p1>{{piece.piece_nb}}</p1>
        </td>
        <td>
            <p1>{{piece.piece_remarques}}</p1>
        </td>
        <td>
            <p1>{{piece.fourni_id}}</p1>
        </td>
        <td>
            <p1>{{piece.local_id}}</p1>
        </td>
        <td>
            <p1>{{piece.commande_fourni_id}}</p1>
        </td>
        <td>
          <a href="{% url 'stock_pieces_velos:indexModifierPiece' piece.piece_num %}">Modifier</a>
        </td>
        <td>
          <a href="#"><img class="imagePoubelle" src="{% static 'img/poubelle.png' %}" alt="Image"></a>
            <!-- {% url 'stock_pieces_velos:indexSupprimerPiece' piece.piece_num %}-->
        </td>
    </tr>
    {% endfor %}

</table>

<a href="{% url 'stock_pieces_velos:indexNouvellePiece' %}" role="button" class="btn btn-primary" aria-pressed="true"
style="margin-left: 10% ">Ajouter une pièce</a>

<!---<div>
    <img src="{% static 'img/veloPieces.jpg' %}" alt="PiecesVelo" width="30" height="40" class="photoStock">
</div>--->

{% endblock %}

BicycletteBleue -Django/stock_pieces_velos/templates/stock_pieces_velos/supprimer_piece.html
<!-- Auteur : Stanley Rochat-->
{% extends 'template_base.html' %}
{% load static %}

{% block contenu %}

        <!-- CSS Libraries -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">




<br>
<h1 style="margin-left: 10%"> Supprimer une pièce </h1>
<br>
<br>
<form action="{% url 'stock_pieces_velos:indexSupprimerPiece' item.piece_num %}" method="post">
    {% csrf_token %}
    <table class="table">
        <thead  class="thead-dark">
        <tr>
        <th class="ligne0">
            <p1>N° pièce</p1>
        </th>
        <th class="ligne0">
            <p1>Type de pièce</p1>
        </th>
        <th class="ligne0">
            <p1>Marque de la pièce</p1>
        </th>
        <th class="ligne0">
            <p1>Type de vélo</p1>
        </th>
        <th class="ligne0">
            <p1>Nombre de pièces</p1>
        </th>
        <th class="ligne0">
            <p1>Fournisseur</p1>
        </th>
        <th class="ligne0">
            <p1>Local</p1>
        </th>
        <th class="ligne0">
            <p1>Commande</p1>
        </th>
    </tr>
</thead>
    <tr>
        <td>
            <p1>{{item.piece_num}}</p1>
        </td>
        <td>
            <p1>{{item.piece_type}}</p1>
        </td>
        <td>
            <p1>{{item.piece_type_velo}}</p1>
        </td>
        <td>
            <p1>{{item.piece_marque}}</p1>
        </td>
        <td>
            <p1>{{item.piece_nb}}</p1>
        </td>
        <td>
            <p1>{{item.fourni_id}}</p1>
        </td>
        <td>
            <p1>{{item.local_id}}</p1>
        </td>
        <td>
            <p1>{{item.commandfourni_id}}</p1>
        </td>
    </tr>

</table>
    <br>
<p1 style="margin-left: 10%"> Êtes-vous sûr de vouloir supprimer cet élément ? </p1>
    <br>
    <a href="{% url 'stock_pieces_velos:indexStockPiecesVelos'%}" class="btn btn-warning" style="margin-left: 10%" >Annuler</a>
    <input class="btn btn-danger" type="submit" name="Confirmer" value="Confirmer">



</form>





{% endblock %}