BicycletteBleue -Django/accueil/urls.py
"""Auteur : Daniele Castro"""

from django.urls import path, include
from . import views

app_name = 'accueil'

urlpatterns = [
    path('',views.home, name="index"),
    path('a_propos/',views.a_propos, name="a_propos"),
    path('contact/',views.contact, name="contact"),
]

BicycletteBleue -Django/bicyclettebleue/urls.py
from django.contrib import admin
from django.urls import path, include
from django_otp.admin import OTPAdminSite

class OTPAdmin(OTPAdminSite):
    pass
from django.contrib.auth.models import User
from django_otp.plugins.otp_totp.models import TOTPDevice

admin_site = OTPAdmin(name= 'OTPAdmin')
admin_site.register(User)
admin_site.register(TOTPDevice)

urlpatterns = [
    path('dadmin/', admin.site.urls),
    path('admin/', admin_site.urls),
    path('',include('accueil.urls')),
    path('location/',include('location.urls')),
    path('client/',include('client.urls')),
    path('compte/',include('compte.urls')),
    path('stock_velos/',include('stock_velos.urls')),
    path('stock_pieces_velos/',include('stock_pieces_velos.urls')),
    path('stock_locaux/',include('stock_locaux.urls')),
    path('réparations/', include('reparation.urls')),
    path('statistique/', include('statistique.urls')),

]

BicycletteBleue -Django/client/urls.py
"""
Auteur : Fatma Aydin
"""
from django.urls import path, include
from . import views

app_name = 'client'

urlpatterns = [
    path('',views.client, name='index'),
    path('nouveauClient/', views.nouveauClient, name='nouveauClient'),
    path('modifierClient/<str:pk>', views.modifierClient, name='modifierClient'),
    path('supprimerClient/<str:pk>', views.supprimerClient, name='supprimerClient'),
]

BicycletteBleue -Django/compte/urls.py
"""
Auteur : Fatma Aydin
"""
from django.urls import path, include
from . import views

app_name = 'compte'

urlpatterns = [
    path('inscription',views.inscriptionPage, name='inscription'),
    path('login',views.loginPage, name='login'),
    path('quitter',views.logoutUser, name='quitter'),
    path('monCompte',views.monCompte, name='monCompte'),
]

BicycletteBleue -Django/location/urls.py
"""
Auteur : Daniele Castro
"""

from django.urls import path, include
from . import views

app_name = 'location'

urlpatterns = [
    path('',views.location, name='index'),
    path('locationEnAttente/', views.locationEnAttente, name='locationEnAttente'),
    path('<int:id>/', views.detailsLocation, name='detailsLocation'),
    path('detailsLocationEnAttente/<int:id>', views.detailsLocationEnAttente, name='detailsLocationEnAttente'),
    path('confirmationLocation/<str:pk>', views.confirmationLocation, name='confirmationLocation'),
    path('nouvelleLocation/', views.nouvelleLocation, name='nouvelleLocation'),
    path('modifierLocation/<str:pk>', views.modifierlocation, name='modifierLocation'),
    path('supprimerLocation/<str:pk>',views.supprimerLocation, name='supprimerLocation'),
    path('refuseLocationEnAttente/<str:pk>',views.refuseLocationEnAttente, name='refuseLocationEnAttente'),



    path('locationClient/<str:pk>',views.locationClient, name='locationClient'),
    path('detailsLocation/<int:id>', views.detailsLocationClient, name='detailsLocationClient'),
    path('nouvelleLocationClient/', views.choixVeloClient, name='choixVeloClient'),
    path('modifierLocationClient/<str:pk>', views.modifierlocationClient, name='modifierLocationClient'),
    path('supprimerLocationClient/<str:pk>', views.supprimerLocationClient, name='supprimerLocationClient'),
    path('finaliserLocationClient/<str:pk>', views.finaliserLocationClient, name='finaliserLocationClient'),
    path('choixVelo/', views.choixVeloClient, name='choixVeloClient'),
    path('donneeLocationClient/<str:pk>', views.donneeLocationClient, name='donneeLocationClient'),
]

BicycletteBleue -Django/reparation/urls.py
from django.urls import path, include
from . import views

app_name = 'reparation'

urlpatterns = [
    path('réparations/', views.reparation, name='indexReparations'),
    path('réparationsDétails/', views.reparation, name='indexReparations'),

]

BicycletteBleue -Django/templates/template_base.html
<!-- Auteur : Daniele Castro
    source template :  https://htmlcodex.com/car-wash-website-template
-->

{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>La bicyclette Bleue</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">

        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    </head>
    <body>
        <!-- Top Bar Start -->
        <div class="top-bar">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 col-md-12">
                        <div class="logo">
                            <a href="{% url 'accueil:index' %}">
                                <img src="{% static 'img/logo.png' %}" alt="Image">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-7 d-none d-lg-block">
                        <div class="row">
                            <div class="col-4">
                                <div class="top-bar-item">
                                    <div class="top-bar-icon">
                                        <i class="far fa-clock"></i>
                                    </div>
                                    <div class="top-bar-text">
                                        <h3>Horaires d'ouverture</h3>
                                        <p>Vendredi et Samedi</p>
                                        <p>14:00 - 19:00</p>

                                    </div>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="top-bar-item">
                                    <div class="top-bar-icon">
                                        <i class="far fa-envelope"></i>
                                    </div>
                                    <div class="top-bar-text">
                                        <h3>Nous contacter</h3>
                                        <p>info@bicyclettebleue.ch</p>
                                        <a href="https://www.instagram.com/bicyclette_bleue/"><img src="{% static 'img/instagram.png' %}" alt="Image" style="width: 35px; height: 35px"></a>
                                        <a href="https://www.facebook.com/bicyclettebleuegeneve/"><img src="{% static 'img/facebook.png' %}" alt="Image" style="width: 37px; height: 37px"></a>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Top Bar End -->

        <!-- Nav Bar Start -->
        <div class="nav-bar">
            <div class="container">
                <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="{% url 'accueil:index' %}" class="nav-item nav-link">Accueil</a>
                            {% if user.is_authenticated and not user.is_superuser%}
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Partie client</a>
                                <div class="dropdown-menu">
                                    <a href="{% url 'location:locationClient' request.user.id %}" class="dropdown-item">Mes locations</a>
                                    <a href="{% url 'location:choixVeloClient' %}" class="dropdown-item">Reserver un vélo</a>
                                    <a href="{% url 'compte:monCompte' %}" class="dropdown-item">Mon compte</a>
                                    <a href="{% url 'reparation:indexReparations' %}" class="dropdown-item">Mes réparations</a>

                                </div>
                            </div>
                            {% elif user.is_superuser %}
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Partie membre</a>
                                <div class="dropdown-menu">
                                    <a href="{% url 'location:index' %}" class="dropdown-item">Location</a>
                                    <a href="{% url 'location:locationEnAttente' %}" class="dropdown-item">Location en attente</a>
                                    <a href="{% url 'client:index' %}" class="dropdown-item">Client</a>
                                    <a href="{% url 'reparation:indexReparations' %}" class="dropdown-item">Réparations</a>
                                    <a href="{% url 'statistique:index' %}" class="dropdown-item">Statistique</a>
                                </div>
                            </div>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Stock</a>
                                <div class="dropdown-menu">
                                    <a href="{% url 'stock_velos:indexStockVelos' %}" class="dropdown-item">Vélos</a>
                                    <a href="{% url 'stock_pieces_velos:indexStockPiecesVelos' %}" class="dropdown-item">Pièces de vélos</a>
                                    <a href="{% url 'stock_locaux:indexStockLocaux' %}" class="dropdown-item">Locaux</a>
                                </div>
                            </div>
                            {% if not user.is_superuser%}
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Partie client</a>
                                <div class="dropdown-menu">
                                    <a href="{% url 'location:locationClient' request.user.id %}" class="dropdown-item">Mes locations</a>
                                    <a href="{% url 'location:choixVeloClient' %}" class="dropdown-item">Reserver un vélo</a>
                                    <a href="{% url 'compte:monCompte' %}" class="dropdown-item">Mon compte</a>
                                </div>
                            </div>
                            {% endif %}
                            {% endif %}
                            <a href="{% url 'accueil:a_propos' %}" class="nav-item nav-link">A propos</a>
                            <a href="{% url 'accueil:contact' %}" class="nav-item nav-link">Contact</a>

                        </div>
                            <div class="nav-item dropdown">
                            {% if user.is_authenticated %}
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> <span>{{request.user}}</span> <img src="{% static 'img/monCompte2.png' %}" alt="Image" style="width: 35px; height: 35px"></a>
                                <div class="dropdown-menu">
                                    <a href="{% url 'location:locationClient'  request.user.id %}" class="dropdown-item">Mes locations</a>
                                    <a href="{% url 'compte:monCompte' %}" class="dropdown-item">Mon compte</a>
                                    <a href="{% url 'compte:quitter' %}" class="dropdown-item">Logout</a>
                                </div>
                            {% else %}
                                <a class="btn btn-custom" href="{% url 'compte:login' %}">Se connecter</a>
                                <a class="btn btn-custom" href="{% url 'compte:inscription' %}">S'inscrire</a>
                            {% endif %}
                            </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->


        <!-- Pre Loader -->
        <div id="loader" class="show">
            <div class="loader"></div>
        </div>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

{% block contenu %}{% endblock %}

<br><br><br>


<foot class="text-center text-lg-start bg-light text-muted">
    <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright :
    <a class="text-reset fw-bold">Bicyclette Bleue</a>
  </div>
  <!-- Copyright -->

</foot>


    </body>
</html>