BicycletteBleue -Django/stock_velos/urls.py
from django.urls import path, include
from . import views

app_name = 'stock_velos'

urlpatterns = [
    path('', views.stock_velos, name='indexStockVelos'),
    path('<int:num>/', views.details_velo, name='indexDetailsVelo'),
    path('detail_velo_client/<int:num>', views.details_veloClient, name='indexDetailsVeloClient'),
    path('nouveau_velo/', views.nouveau_velo, name='indexNouveauVelo'),
    path('modifier_velo/<str:pk>', views.modifier_velo, name='indexModifierVelo'),
    path('supprimer_velo/<str:pk>', views.supprimer_velo, name='indexSupprimerVelo'),
]

BicycletteBleue -Django/stock_velos/templates/stock_velos/ajouter_velos.html
<!-- Auteur : Stanley Rochat-->
{% extends 'template_base.html' %}
{% load static %}

{% block contenu %}


        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">




<form style="margin-left: 25% ; margin-right: 30%" action="" method="post">
    {% csrf_token %}
    <!-- <p1> Photo: </p1> {{formVelo.vel_photo}} -->
    <br>
    <h1> Ajouter un vélo </h1>

    <br>
    <br>

    <div class="form-group">
     <p1>Numéro cadre<p1 style="color: red">*</p1>: &nbsp; </p1>
    <input  class="form-control"  for={{formVelo.vel_num_cadre}}
    </div>

    <div class="form-group">
    <p1>Nom<p1 style="color: red">*</p1>: &nbsp; </p1>
    <input  class="form-control"  for={{formVelo.vel_nom}}
    </div>

    <div class="form-group">
    <p1>Type<p1 style="color: red">*</p1>: &nbsp; </p1>
    <select  class="form-control"  for={{formVelo.vel_type}}
    </div>

    <div class="form-group">
    <p1>Marque<p1 style="color: red">*</p1>: &nbsp; </p1>
    <select  class="form-control" for={{formVelo.vel_marque}}
    </div>

    <div class="form-group">
    <p1>Couleur<p1 style="color: red">*</p1>: &nbsp; </p1>
    <select  class="form-control"   for={{formVelo.vel_couleur}}
    </div>

    <div class="form-group">
    <p1>Etat<p1 style="color: red">*</p1>: &nbsp; </p1>
    <select  class="form-control"   for={{formVelo.vel_etat}}
    </div>

    <div class="form-group">
    <p1>Statut<p1 style="color: red">*</p1>: &nbsp; </p1>
    <select  class="form-control"    for={{formVelo.vel_statut}}
    </div>

     <div class="form-group">
    <p1>Remarque: &nbsp; </p1>
    <input  class="form-control"    for={{formVelo.vel_remarque}}
    </div>

     <div class="form-group">
    <p1>Local<p1 style="color: red">*</p1>: &nbsp; </p1>
    <select  class="form-control"    for={{formVelo.local_id}}
    </div>

    <div class="form-group">
    <p1>Donateur: &nbsp; </p1>
    <select  class="form-control"    for={{formVelo.don_id}}
    </div>

     <div class="form-group">
    <p1>Photo: &nbsp; </p1>
    <input  class="form-control"   for={{formVelo.vel_photo}}
    </div>


    <br>
<div>
    <a href="{% url 'stock_velos:indexStockVelos'%}"  class="btn btn-primary" >Annuler</a>
    <input type="submit" class="btn btn-primary" role="button">
</div>


</form>
<br>
<sup style="color: red ; margin-left: 25%">*Champs obligatoires</sup>



{% endblock %}

BicycletteBleue -Django/stock_velos/templates/stock_velos/detailsVelo.html
<!---
Auteur : Stanley Rochat
-->


{% extends 'template_base.html' %}
{% load static %}
{% block contenu %}

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">


    <br>
    <h1 class="detailLocation"> Les détails du vélo :</h1>
    <br>
    <div class="detailLocation">
        <img src="{% static 'img/velo/velo1.png' %}" alt="" style="width: 350px; height: 280px"><br><br>
        {{velo.vel_photo}} <br>
        Nom : {{ velo.vel_nom}} <br>
        N° : {{velo.vel_num}} <br>
        Numéro cadre : {{velo.vel_num_cadre}} <br>
        Local : {{velo.local_id}} <br>

        {% if velo.don_id %}}
        Donateur : {{velo.don_id}} <br>
        {% else %}
        Donateur : Aucun <br>
        {% endif %}

        Etat du vélo : {{velo.vel_etat}} <br>
        <br>
        Type : {{ velo.vel_type }} <br>
        Marque : {{ velo.vel_marque}} <br>
        Couleur : {{ velo.vel_couleur }} <br>
        <br>
        Statut de location : {{ velo.vel_statut }} <br>

        {% if velo.vel_remarque %}
        Remarques : {{velo.vel_remarque}} <br>
        {% else %}
        Remarques : <br>
        {% endif %}


        <a href="{% url 'stock_velos:indexStockVelos' %}" class="btn btn-primary" role="button" aria-pressed="true"
           style="margin-top: 2%"> <--- Retour au stock de velos </a>
    </div>

<br><br>




{% endblock contenu %}

BicycletteBleue -Django/stock_velos/templates/stock_velos/detailsVeloClient.html
<!---
Auteur : Daniele Castro
-->


{% extends 'template_base.html' %}
{% load static %}
{% block contenu %}

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">


    <br>
    <h1 class="detailLocation"> Les détails du vélo :</h1>
    <br>
    <div class="detailLocation">
        <img src="{% static 'img/velo/velo1.png' %}" alt="" style="width: 350px; height: 280px"><br><br>
        Nom : {{ velo.vel_nom }} <br>
        Marque: {{ velo.vel_marque}} <br>
        Couleur : {{ velo.vel_couleur }} <br>
        Type : {{ velo.vel_type }} <br><br>

        {% if nbLocationEnCours >= 3 %}
            {{messageErreur}}
        {% else %}
            <a href="{% url 'location:donneeLocationClient' velo.vel_num %}" class="btn btn-primary" role="button" aria-pressed="true" style="margin-bottom:20px">Je prends !</a><br>
        {% endif  %}
        <a href="{% url 'location:choixVeloClient' %}"> <--- Retour aux velos </a>
    </div>

<br><br><br><br>




{% endblock contenu %}

BicycletteBleue -Django/stock_velos/templates/stock_velos/stock_velos.html
<!-- Auteur : Stanley Rochat-->
{% extends 'template_base.html' %}
{% load static %}

{% block contenu %}

        <!-- CSS Libraries -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">


<br>

<h1 style="margin-left: 10%">Stock de vélos</h1>
<br>
<br>

<!-- <a class="btn btn-danger" aria-pressed="true"
   style="margin: 0% 0% 3px 1820px; color: white">Supprimer</a>
-->

<table class="table">
    <thead class="thead-dark">
    <tr>
        <th class="ligne0">
            <p1>Photo</p1>

        <th class="ligne0">
            <p1>N°</p1>
        </th>
        <th class="ligne0">
            <p1>N° cadre</p1>
        </th>
        <th class="ligne0">
            <p1>Nom</p1>
        </th>
        <th class="ligne0">
            <p1>Type</p1>
        </th>
        <th class="ligne0">
            <p1>Marque</p1>
        </th>
        <th class="ligne0">
            <p1>Couleur</p1>
        </th>
        <th class="ligne0">
            <p1>Etat</p1>
        </th>
        <th class="ligne0">
            <p1>Statut</p1>
        </th>
        <th class="ligne0">
            <p1>Remarque</p1>
        </th>
        <th class="ligne0">
            <p1>Local</p1>
        </th>
        <th class="ligne0">
            <p1>Donateur</p1>
        </th>
        <th class="ligne0">
            <p1></p1>
        </th>
        <th class="ligne0">
            <p1></p1>
        </th>
    </tr>
    </thead>
    {% for velo in velosObjets %}
    <tr>
        <!---<td>
            <input type="checkbox" name="select">
        </td>-->
        <td>
            <img src="{% static 'img/velo/non.png' %}" alt="Image" style="width: 35px; height: 35px">
        </td>
        <td>
            <p1>{{velo.vel_num}}</p1>
        </td>
        <td>
            <p1>{{velo.vel_num_cadre}}</p1>
        </td>
        <td>
            <p1><a href="{% url 'stock_velos:indexDetailsVelo' velo.vel_num %}">{{velo.vel_nom}}</a></p1>
        </td>
        <td>
            <p1>{{velo.vel_type}}</p1>
        </td>
        <td>
            <p1>{{velo.vel_marque}}</p1>
        </td>
        <td>
            <p1>{{velo.vel_couleur}}</p1>
        </td>
        <td>
            <p1>{{velo.vel_etat}}</p1>
        </td>
        <td>
            <p1>{{velo.vel_statut}}</p1>
        </td>
        <td>
            <p1>{{velo.vel_remarque}}</p1>
        </td>
        <td>
            <p1>{{velo.local_id}}</p1>
        </td>
        <td>
            <p1>{{velo.don_id}}</p1>
        </td>
        <td>
          <a href="{% url 'stock_velos:indexModifierVelo'  velo.vel_id%}">Modifier</a>
        </td>
        <td>
          <a href="{% url 'stock_velos:indexSupprimerVelo' velo.vel_id%}"><img class="imagePoubelle" src="{% static 'img/poubelle.png' %}" alt="Image"></a>
        </td>
    </tr>
    {% endfor %}

</table>

<a href="{% url 'stock_velos:indexNouveauVelo' %}" role="button" class="btn btn-primary" aria-pressed="true"
style="margin-left: 10% ">Ajouter un vélo</a>


<!---<div>
    <img src="{% static 'img/about.jpg' %}" alt="Velo" width="30" height="40" class="photoStock">
</div>-->

{% endblock %}

BicycletteBleue -Django/stock_velos/templates/stock_velos/supprimer_velo.html
<!-- Auteur : Stanley Rochat-->
{% extends 'template_base.html' %}
{% load static %}

{% block contenu %}

        <!-- CSS Libraries -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">




<br>
<h4 style="margin-left: 22%">Voulez-vous vraiment supprimer ce vélo?</h4>
<br>
<br>
<form action="{% url 'stock_velos:indexSupprimerVelo' item.vel_id %}" method="post">
    {% csrf_token %}
    <table class="table">
        <thead  class="thead-dark">
    <tr>
        <th class="ligne0">
            <p1>Photo</p1>
        </th>
        <th class="ligne0">
            <p1>ID</p1>
        </th>
        <th class="ligne0">
            <p1>N° cadre</p1>
        </th>
        <th class="ligne0">
            <p1>Nom</p1>
        </th>
        <th class="ligne0">
            <p1>Type</p1>
        </th>
        <th class="ligne0">
            <p1>Marque</p1>
        </th>
        <th class="ligne0">
            <p1>Couleur</p1>
        </th>
        <th class="ligne0">
            <p1>Etat</p1>
        </th>
        <th class="ligne0">
            <p1>Statut</p1>
        </th>
        <th class="ligne0">
            <p1>Remarque</p1>
        </th>
        <th class="ligne0">
            <p1>Local</p1>
        </th>
        <th class="ligne0">
            <p1>Donateur</p1>
        </th>
    </tr>
    </thead>
    <tr>
        <td>
            <p1>{{item.vel_photo}}</p1>
        </td>
        <td>
            <p1>{{item.vel_id}}</p1>
        </td>
        <td>
            <p1>{{item.vel_num_cadre}}</p1>
        </td>
        <td>
            <p1>{{item.vel_nom}}</p1>
        </td>
        <td>
            <p1>{{item.vel_type}}</p1>
        </td>
        <td>
            <p1>{{item.vel_marque}}</p1>
        </td>
        <td>
            <p1>{{item.vel_couleur}}</p1>
        </td>
        <td>
            <p1>{{item.vel_etat}}</p1>
        </td>
        <td>
            <p1>{{item.vel_statut}}</p1>
        </td>
        <td>
            <p1>{{item.vel_remarque}}</p1>
        </td>
        <td>
            <p1>{{item.local_id_id}}</p1>
        </td>
        <td>
            <p1>{{item.don_id_id}}</p1>
        </td>
    </tr>

</table>
    <br>
    <br>
    <a href="{% url 'stock_velos:indexStockVelos'%}"  class="btn btn-primary" style="margin-left: 22%">Annuler</a>
    <input class="btn btn-danger" type="submit" value="Supprimer" name="Confirmer" >


</form>





{% endblock %}